development:
  adapter: mysql2
  encoding: utf8
  database: JDpal_local
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: JDpal_test
  host: localhost
  username: root
  password:

production: 
  adapter: postgresql 
  encoding: unicode
