development:
  address: "smtp.gmail.com"
  port: 587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "jdpalservice@gmail.com"
  password: "jdpal2016"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "jdpalservice@gmail.com"
  password: "jdpal2016"
  enable_starttls_auto: true